### ISSUE TITLE
Final Code Review

### ISSUE THREAD

**Issue by zxc0328** [Muxi-Studio/MuxiAuth-fe#2]
分两方面来说，一方面是UI相关的：

1. 两倍图的问题，不懂可以问wwy
2. 设计师的图有时候会有问题（当然，看和你合作的设计师的水平，这次张贝贝这样的她就是比较初级的水平，有时候会出点小问题，你要留意。如果设计师是老手的话一般不会轮到你来指出问题，毕竟专业的设计是非常专业的），比如桌面版，木犀通行证的logo和下面的圆形的图，明显应该是左对齐的（你有空可以看一下《写给大家看的设计师》，里面说了几条最常用的原则）。这个时候你应该和设计师沟通，然后改过来。
3. 字体没设置好，有问题问wwy。
4. 底部的导航应该是有内容的，copy right一类的。比如 Hello from Wuhan, 204-2017 Muxistudio
5. 桌面版，右边的表单，宽度应该是固定的。这是一个定宽居中布局。`.main`应该是定宽的，和上面的导航栏的container宽度一样。
6. 移动版顶部logo和下面的内容直接的间距明显太小了，你可以和设计师讨论一下。我建议变大一些。
7. 登录和注册两个，我觉得某一个选中的话，那个应该有个高亮或者什么效果，不然完全看不出现在是在哪个界面。你可以和设计师讨论一下。
8. 移动版底部也加上copy right吧。这个页面不一定是要高度100%的，有滚动条也行。然后底部三个链接的设置我觉得有问题，你要么就三等分然后各自居中不就行了，为啥左边加了margin。

还有一方面是业务逻辑上的：

1. `if (this.emailInput && this.passwordInput && this.$v.emailInput.email) {`这里你是想验证email和password是不是有值对吧？其实这个是有一个验证函数的，就是require，你看一下文档就有。
2. 多个有关联的验证，可以设置一个group，group的状态是根据group里的各个字段整合而来的，所以以后submit的时候只要看这个group的属性就可以判断整个表单的情况了，不用再自己写判断
3. `email`有一个验证是，不能和已经注册的重复，这个是有一个API的。你需要自己封装一个自定义的验证函数，异步的。文档里有说异步验证函数。
4. 看你最新的submit里有发请求的逻辑，email那个验证是作为验证函数，和普通验证一样的，不是最后才验证的。最后submit只是看一下group是不是通过状态，如果通过了就发请求提交表单这样。
5. 图片等资源用webpack加载吧。

**Comment by zxc0328** [comment]
4月7日Review

PC版 CSS

+ 底部footer的木犀团队加一个到我们官网的链接
+ logo要加链接到主页，这个是常识
+ SEO信息和favicon还是没加
+ header的容器（985px宽）里面是定宽布局，所以为啥logo的margin是百分比。中间容器里也是一样的，把百分比的padding什么的都改成固定值。
+ headr容器里面所有子元素是用浮动水平布局的，如果用浮动的话就要清除浮动。你现在没有看出问题是因为你给父元素设置了高度，但是实际上父元素是不用设置高度的。因为高度是从内向外撑开的。你去掉高度看看，父元素高度就变0了。清除浮动之后高度就OK了。
+ 左边那个图，垂直居中用的`margin: 15% auto`，这怎么可能居中啊
+ 表单输入框那里，用一个`.height`div元素当margin用，逗我吗，HTML代码是结构，CSS是样式，两者要分离。

待续

**Comment by zxc0328** [comment]
4月13日Review

`login.vue`

+ 你用了验证插件，那验证的实现，就采用了这个既定的模式。是模式，要么就完全不用，要么就乖乖的遵守。开发的时候很多时候都是这样，会有很多帮你把代码理的更清楚的条条框框。
验证插件的模式要求所有的验证函数都是固定的格式，那你现在用的验证函数是内置的，验证的逻辑明显是有很多种的，验证插件提供的不能满足，比如检查邮箱是不是已经被注册了，但验证插件提供了API给你，你可以自定义验证函数，这个自定义的验证函数和内置的在API上是一模一样的。
所以如果遇到自定义的验证逻辑，你应该自定义验证函数，然后这个验证函数还比较特殊，是异步的。文档里有说。
原因是什么，你自己想想。我上面也已经讲了。
+ 同样，Vue是一个MVVM框架，template和style里面的是View。你写的script里面的是VM。有关样式的应该属于View层。**这两个是分离的**。所以
```
computed: {
            changedButton: function() {
                return {
                    'background-color': this.submitFlag ? 'grey' : '#fd860e'
                }
            }
        },
```
这个就很奇怪了。如果要写数据和样式对应的逻辑，那直接在template里面写就行。VM处理的是数据相关的逻辑。还有一个就是` '#fd860e'`这个是什么鬼，你写一个class就行啊。一般控制样式切换就是控制class的变换。

待续

**Comment by Cruyun** [comment]
https://github.com/Muxi-Studio/MuxiAuth-fe/commit/01530a1c7d8fa63e87e99a7dce519afd28dc4792   
https://github.com/Muxi-Studio/MuxiAuth-fe/commit/43b9c3444f5c912b07c194fc8197ae395488e121
应该差不多啦，抱歉拖了好久
