### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Amanda111** [Muxi-Studio/MuxiAuth-fe#3]
**login.vue**

1. 写组件样式的时侯需要加上“scoped”，或者用css module，可以看一下zindex大神的[这篇博客](http://zxc0328.github.io/2016/11/12/css-modules/)。不进行处理的话会影响全局。可以看一下login组件里的`.height`现在应用的是写在哪个组件里的样式。

如果两个组件用的是同样的样式可以写一份scss import进来。

2.  “忘记密码”`.class` 和 “邮箱格式有误”`.check`,字体的样式都是一样的，可以写一个提示字体样式的class

3.  focus的时候好像不需要自己写什么事件。所以`isFocus`具体做了什么事情？这里的业务逻辑是什么样的？

**Comment by Cruyun** [comment]
focus是用来处理点了submitbutton的，点击submit之后不能再次点击，假如validate不通过，重新focus input框修改内容就可以再次submit。
scoped加在哪？

**Comment by Amanda111** [comment]
明白了。scoped加在style tag里面😏

**Comment by Cruyun** [comment]
https://github.com/Muxi-Studio/MuxiAuth-fe/commit/76df59991b33bc73b4a73a28dab73724bfb93a9a
学姐我改啦~你看看行不？
